In [8]:
import os
import jpy_commons as jpy
import jpy_class_selection as sel

In [2]:
data = jpy._test_data
display(data)

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,...,1.156514e+06,3.946027e+06,12764.529300,1.276453e+06,False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,...,9.504252e+05,3.242851e+06,51450.816410,5.145082e+06,False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,...,1.451544e+07,4.952666e+07,14938.000000,1.493800e+06,False,NaN,Compliant,NaN,2089.28,2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,98101.0,0659000640,...,8.115253e+05,2.768924e+06,18112.130860,1.811213e+06,False,NaN,Compliant,NaN,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,98121.0,0659000970,...,1.573449e+06,5.368607e+06,88039.984380,8.803998e+06,False,NaN,Compliant,NaN,505.01,2.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3371,50222,2016,Nonresidential COS,Office,Horticulture building,1600 S Dakota St,Seattle,WA,NaN,1624049080,...,1.536550e+05,5.242709e+05,3254.750244,3.254750e+05,True,NaN,Error - Correct Default Data,NaN,20.94,1.70
3372,50223,2016,Nonresidential COS,Other,International district/Chinatown CC,719 8th Ave S,Seattle,WA,NaN,3558300000,...,1.162210e+05,3.965461e+05,5537.299805,5.537300e+05,False,NaN,Compliant,NaN,32.17,2.01
3373,50224,2016,Nonresidential COS,Other,Queen Anne Pool,1920 1st Ave W,Seattle,WA,NaN,1794501150,...,5.252517e+05,1.792159e+06,39737.390630,3.973739e+06,False,NaN,Compliant,NaN,223.54,16.99
3374,50225,2016,Nonresidential COS,Mixed Use Property,South Park Community Center,8319 8th Ave S,Seattle,WA,NaN,7883603155,...,1.022480e+05,3.488702e+05,3706.010010,3.706010e+05,False,NaN,Compliant,NaN,22.11,1.57
3375,50226,2016,Nonresidential COS,Mixed Use Property,Van Asselt Community Center,2820 S Myrtle St,Seattle,WA,NaN,7857002030,...,1.267744e+05,4.325542e+05,7203.419922,7.203420e+05,False,NaN,Compliant,NaN,41.27,2.26

In [9]:
sel.test_normalize_operands(data)

test 1 : one bool array
type : <class 'pandas.core.series.Series'>
size : 3376
dtype : <class 'numpy.bool_'>
single operand

test 2 : 2 bool arrays
type : <class 'list'>
size : 2
dtype : <class 'pandas.core.series.Series'>
vector of operands

test 3 : one index
type : <class 'pandas.core.indexes.numeric.Int64Index'>
size : 1460
dtype : <class 'numpy.int64'>
single operand

test 4 : 2 indexes
type : <class 'list'>
size : 2
dtype : <class 'pandas.core.indexes.numeric.Int64Index'>
vector of operands

test 5 : one indices
type : <class 'numpy.ndarray'>
size : 1460
dtype : <class 'numpy.int32'>
single operand

test 6 : 2 indices
type : <class 'list'>
size : 2
dtype : <class 'numpy.ndarray'>
vector of operands

In [4]:
sel.test_eval_after_normalize(data)

type : <class 'list'>
size : 2
dtype : <class 'pandas.core.series.Series'>
vector of operands
(2, 3376)
(<class 'list'>, <class 'pandas.core.series.Series'>)
index size : 3376

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
32,38,2016,NonResidential,Small- and Mid-Sized Office,Good Shepherd Center,4649 Sunnyside Ave. N.,Seattle,WA,98070.0,0825049008,...,3.964957e+05,1352843.0,27930.77148,2793077.0,False,NaN,Compliant,NaN,157.77,1.81
39,52,2016,NonResidential,Small- and Mid-Sized Office,SBC52,5305 Shilshole Ave NW,Seattle,WA,98107.0,0467000429,...,1.257792e+06,4291585.0,18948.75977,1894876.0,False,NaN,Compliant,NaN,130.56,1.38
40,53,2016,NonResidential,Small- and Mid-Sized Office,El Centro de la Raza,2524 16th Ave S,Seattle,WA,98144.0,0570000340,...,4.629980e+05,1579749.0,13715.82031,1371582.0,False,NaN,Compliant,NaN,83.86,1.60
44,57,2016,NonResidential,Large Office,5th and Pine,413 Pine Street,Seattle,WA,98101.0,1975700200,...,2.794889e+06,9536160.0,0.00000,0.0,False,NaN,Compliant,NaN,66.48,0.40
46,59,2016,NonResidential,Small- and Mid-Sized Office,Gibraltar Tower,1520 3rd Ave,Seattle,WA,98101.0,1975700380,...,1.486510e+06,5071973.0,0.00000,0.0,False,NaN,Compliant,NaN,35.36,0.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3312,50026,2016,NonResidential,Small- and Mid-Sized Office,Chophouse Row,1424 11th Ave,Seattle,WA,98122.0,6003500255,...,3.787091e+05,1292155.0,10545.37012,1054537.0,False,NaN,Compliant,NaN,65.01,1.72
3317,50031,2016,NonResidential,Large Office,Dexter Station,1101 Dexter Ave. N.,Seattle,WA,98109.0,2249500265,...,4.968672e+06,16953109.0,18076.54883,1807655.0,False,NaN,Compliant,NaN,214.19,0.42
3320,50037,2016,NonResidential,Large Office,"MAPS 325 Ninth Avenue North, LLC",325 9th Avenue North,Seattle,WA,98109.0,1991201265,...,3.356673e+06,11452968.0,12670.99023,1267099.0,False,NaN,Compliant,NaN,147.14,0.31
3324,50045,2016,NonResidential,Large Office,"Sidneysea, LLC",400 9th Avenue North,Seattle,WA,98109.0,1983200035,...,3.438751e+06,11733018.0,22656.19141,2265619.0,False,NaN,Compliant,NaN,202.12,0.42
3339,50069,2016,NonResidential,Small- and Mid-Sized Office,Airport - Main Terminal,7277 Perimeter Rd.,Seattle,WA,98108.0,2824049007,...,6.351199e+05,2167029.0,22536.21094,2253621.0,False,NaN,Compliant,NaN,134.80,5.39

In [5]:
sel.test_display_selector()

&
  assert[ComplianceStatus, Compliant]
  |
    assert[BuildingType, Multifamily]
    assert[PrimaryPropertyType, Multifamily]
  ~
    |
      assert[BuildingType, Campus]
      assert[BuildingType, NonResidential]

In [6]:
sel.test_instance_selector(data)

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
9,13,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Lyon Building,607 - 3rd Ave.,Seattle,WA,98104.0,0939000105,...,7.420912e+05,2532015.0,10020.259770,1002026.0,False,NaN,Compliant,NaN,151.12,2.37
165,265,2016,Multifamily MR (5-9),Mid-Rise Multifamily,YWCA Opportunity Place,2024 3rd Avenue,Seattle,WA,98121.0,8729690000,...,1.612728e+06,5502627.0,45374.941410,4537494.0,False,NaN,Compliant,NaN,279.35,2.39
173,280,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Wintonia,1431 Minor Ave,Seattle,WA,98101.0,8725600350,...,4.903724e+05,1673151.0,25164.187500,2516419.0,False,NaN,Compliant,NaN,145.31,2.80
188,296,2016,Multifamily LR (1-4),Low-Rise Multifamily,Cooper School Artist's Lofts,4408 Delridge Way SW,Seattle,WA,98106.0,3388120000,...,3.493257e+05,1191899.0,7947.119629,794712.0,False,NaN,Compliant,NaN,50.52,0.89
189,297,2016,Multifamily MR (5-9),Mid-Rise Multifamily,LAKE CITY COURT,12730 33RD AVE NE,Seattle,WA,98125.0,3993000000,...,4.558248e+05,1555274.0,9186.879883,918688.0,False,NaN,Compliant,NaN,59.63,1.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3353,50090,2016,Multifamily MR (5-9),Mid-Rise Multifamily,131910 - LIV Seattle,4717 Brooklyn Ave NE,Seattle,WA,98105.0,8817400110,...,4.407752e+05,1503925.0,8337.259766,833726.0,False,NaN,Compliant,NaN,54.76,0.86
3354,50092,2016,Multifamily MR (5-9),Residence Hall,Terry Hall & Maple Hall,1101 NE Campus Pkwy,Seattle,WA,98195.0,1142002345,...,2.583406e+06,8814581.0,76529.031250,7652903.0,False,NaN,Compliant,NaN,467.90,1.44
3355,50093,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Raven Terrace,820 Yesler Way,Seattle,WA,98104.0,9822000080,...,6.334232e+05,2161240.0,0.000000,0.0,False,NaN,Compliant,NaN,15.07,0.18
3357,50095,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Broadstone Sky,4745 40th Ave SW,Seattle,WA,98116.0,7579200395,...,5.828756e+05,1988772.0,15634.129880,1563413.0,False,NaN,Compliant,NaN,96.90,0.47
3358,50098,2016,Multifamily LR (1-4),Low-Rise Multifamily,1806,1806 23rd Avenue,Seattle,WA,98122.0,1407300010,...,1.465200e+05,499926.0,2899.209961,289921.0,False,NaN,Compliant,NaN,18.88,0.93

In [7]:
# compositions simple
sel.test_compound_instance_selector(data)

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
9,13,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Lyon Building,607 - 3rd Ave.,Seattle,WA,98104.0,0939000105,...,7.420912e+05,2532015.0,10020.259770,1002026.0,False,NaN,Compliant,NaN,151.12,2.37
22,28,2016,SPS-District K-12,K-12 School,Graham Hill Elementary,5149 S. Graham St.,Seattle,WA,98118.0,1102000138,...,2.746059e+05,936955.0,6025.229004,602523.0,True,NaN,Error - Correct Default Data,NaN,38.53,0.69
28,34,2016,SPS-District K-12,K-12 School,Meany Building,301/300 21st Ave. E.,Seattle,WA,98112.0,0688000090,...,0.000000e+00,0.0,0.000000,0.0,False,NaN,Missing Data,NaN,0.00,0.00
30,36,2016,SPS-District K-12,K-12 School,Jane Addams Middle,11051 34th Ave. N.E.,Seattle,WA,98125.0,0752000170,...,5.708092e+05,1947601.0,48315.718750,4831572.0,True,NaN,Error - Correct Default Data,NaN,270.18,1.68
31,37,2016,SPS-District K-12,K-12 School,John Hay Elementary,201 Garfield St.,Seattle,WA,98109.0,0809000005,...,4.386917e+05,1496816.0,0.000000,0.0,False,NaN,Missing Data,NaN,10.43,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3353,50090,2016,Multifamily MR (5-9),Mid-Rise Multifamily,131910 - LIV Seattle,4717 Brooklyn Ave NE,Seattle,WA,98105.0,8817400110,...,4.407752e+05,1503925.0,8337.259766,833726.0,False,NaN,Compliant,NaN,54.76,0.86
3354,50092,2016,Multifamily MR (5-9),Residence Hall,Terry Hall & Maple Hall,1101 NE Campus Pkwy,Seattle,WA,98195.0,1142002345,...,2.583406e+06,8814581.0,76529.031250,7652903.0,False,NaN,Compliant,NaN,467.90,1.44
3355,50093,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Raven Terrace,820 Yesler Way,Seattle,WA,98104.0,9822000080,...,6.334232e+05,2161240.0,0.000000,0.0,False,NaN,Compliant,NaN,15.07,0.18
3357,50095,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Broadstone Sky,4745 40th Ave SW,Seattle,WA,98116.0,7579200395,...,5.828756e+05,1988772.0,15634.129880,1563413.0,False,NaN,Compliant,NaN,96.90,0.47
3358,50098,2016,Multifamily LR (1-4),Low-Rise Multifamily,1806,1806 23rd Avenue,Seattle,WA,98122.0,1407300010,...,1.465200e+05,499926.0,2899.209961,289921.0,False,NaN,Compliant,NaN,18.88,0.93